WIP: add styled components
denisfl/adidas pull request #2
Opened 2017-05-12 16:21 UTC by denisfl

2017-05-12 16:27 UTC, denisfl commented on src/Menu/styled.js
> +  .is-active & {
@evgenyrodionov мне не оч нравится этот каскад. можно ли это оформить как-то лучше?
в css это было `.menu-item.is-active .menu-item-link` и в целом ок. тут хз, возможно есть более элегантный способ.

2017-05-12 16:30 UTC, denisfl commented
Из оставшегося: 
- [ ] перевести все элементы в стайлед компонентс
- [ ] добавить реакт-флекбокс-грид
- [ ] ну и комментики

2017-05-12 18:43 UTC, evgenyrodionov commented on src/Menu/styled.js
> +  .is-active & {
Почему бы не стилизовать .menu-item-link?

2017-05-12 18:44 UTC, imevro approved these changes
Норм всё

2017-05-13 18:26 UTC, imevro requested changes
В целом хорошо, но надо доделать мелочи

2017-05-13 18:26 UTC, evgenyrodionov commented on src/Filters/FilterSex.jsx
> +class FilterSex extends Component {
1) в функциональный компонент
2) в лямбда-фукнцию
3) экспорт дефолт сразу, не создавай лишнюю переменную

2017-05-13 18:26 UTC, evgenyrodionov commented on src/Filters/FilterSize.jsx
> +import React, { Component } from 'react';
Тут тоже

2017-05-13 18:26 UTC, evgenyrodionov commented on src/Filters/index.jsx
> +import { FiltersWrapper, FiltersIcon } from './styled';
фильтр фильтр фильтр фильтр фильтр ты канье уэст что ли с его йиззи йиззи йиззи

Убирай эти префиксы

2017-05-13 18:26 UTC, evgenyrodionov commented on src/Product/List/index.jsx
> +import ProductCard from './Card';
Ты и так в продакт

2017-05-13 18:26 UTC, evgenyrodionov commented on src/index.js
>  import '../node_modules/normalize.css/normalize.css';
import 'normalize'css'

2017-05-13 18:26 UTC, evgenyrodionov commented on src/index.js
>  import '../node_modules/flexboxgrid/css/flexboxgrid.min.css';
тоже

2017-05-13 19:21 UTC, denisfl commented on src/index.js
>  import '../node_modules/flexboxgrid/css/flexboxgrid.min.css';
flexboxgrid.min.css - вообще лишнее, я ж на реакт-либу перешёл.

2017-05-13 19:22 UTC, denisfl commented on src/Filters/index.jsx
> +import { FiltersWrapper, FiltersIcon } from './styled';
эхо css-нейминга без изоляции

2017-05-13 22:58 UTC, imevro approved these changes
Норм, но жду интеграции с трэвисом, чтобы проверить линтер. После этого смерджу.

2017-05-14 11:47 UTC, denisfl commented
@evgenyrodionov с трэвисом интегрирован. от меня еще что-то требуется?

2017-05-14 14:34 UTC, imevro approved these changes
Норм

2017-05-14 14:34 UTC, merged